import type { Metadata } from "next";
import { GoogleTagManager } from "@next/third-parties/google";
import StepperLayout from "#components/StepperLayout";
import { clientEnv } from "#env/client";
import { getFooterProps } from "#utils/getFooterProps";

export const metadata: Metadata = {
  title: "Roadside Assistance - Change My Vehicle",
  description: "Generated by create next app",
};

export default function Layout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const { NEXT_PUBLIC_RAC_HOMEPAGE_URL, NEXT_PUBLIC_ROADSIDE_ASSISTANCE_ENTITLEMENTS_URL, NEXT_PUBLIC_GTM_ID } =
    clientEnv();

  return (
    <>
      <StepperLayout
        racHomepageUrl={NEXT_PUBLIC_RAC_HOMEPAGE_URL}
        entitlementsUrl={NEXT_PUBLIC_ROADSIDE_ASSISTANCE_ENTITLEMENTS_URL}
        footerProps={getFooterProps()}
      >
        {children}
      </StepperLayout>
      <GoogleTagManager gtmId={NEXT_PUBLIC_GTM_ID} />
    </>
  );
}
