---
exclude_paths:
  - '**.gitignore'
  - '**/.dockerignore'
  - '**.gitattributes'
  - '**.editorconfig'
  - '**.codacy.yaml'
  - '**.md'
  - '.storybook/**'
  - '.vscode/**'
  - 'docs/**'
  - '**/*.stories.tsx'
  - '**/styles.ts'
  - '*.json'
  - '.github/**'
  - '**/types.ts'
  - '**/*.test.tsx'
  - '**/*.e2e.tsx'
  - '**/storybook/**'
  - '**/tooling/**'
  - '**/turbo/**'
  - 'tests/**'
  - '**/Properties/AssemblyInfo.cs'
