membership-subgraph:
  properties:
    configuration:
      registries:
        - server: racwa.azurecr.io
          username: ''
          passwordSecretRef: ''
          identity: /subscriptions/4b737f05-03e2-4b5a-88a4-aa8264a39bed/resourceGroups/rg-next-rac-com-au-npe/providers/Microsoft.ManagedIdentity/userAssignedIdentities/next-rac-identity-npe
    template:
      containers:
        - image: racwa.azurecr.io/rac-digital/membership-subgraph
          name: membership-subgraph
          resources:
            cpu: 0.25
            memory: 0.5Gi
          securityContext:
            allowPrivilegeEscalation: false
          env:
            - name: APIM__ApiKey
              secretRef: digital-content-api-subscription-key
            - name: AzureMonitor__ConnectionString
              secretRef: app-insights-connection-string
            - name: ASPNETCORE_ENVIRONMENT
              value: dev
      scale:
        minReplicas: 1
        maxReplicas: 1

  identity:
    type: UserAssigned
    userAssignedIdentities:
      - /subscriptions/4b737f05-03e2-4b5a-88a4-aa8264a39bed/resourceGroups/rg-next-rac-com-au-npe/providers/Microsoft.ManagedIdentity/userAssignedIdentities/next-rac-identity-npe
