export const styles = {
  ctaBannerSection: (imageUrl: string) => ({
    position: "relative",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    height: { xs: "436px", md: "480px" },
    backgroundImage: `url("${imageUrl}")`,
    backgroundSize: "cover",
    backgroundPosition: "center",
  }),
  ctaBannerContainer: (contentPosition: string) => ({
    display: "flex",
    justifyContent: contentPosition === "Left" ? "flex-start" : "flex-end",
  }),
  ctaBannerOverlay: (contentPosition: string) => ({
    position: "absolute",
    height: "100%",
    top: 0,
    left: contentPosition === "Left" ? { xs: 0, md: "auto" } : "auto",
    right: contentPosition === "Right" ? { xs: 0, md: "auto" } : "auto",
    backgroundColor: "rgba(0, 22, 48, 0.6)",
    color: "#fff",
    px: { xs: 0, md: "24px" },
    maxWidth: { xs: "100%", md: "496px" },
    width: "100%",
    borderRadius: "0",
    display: "flex",
    alignItems: { xs: "center", md: "flex-start" },
    textAlign: { xs: "center", md: "left" },
    justifyContent: "center",
    flexDirection: "column",
    backdropFilter: "blur(3px)",
  }),
  ctaBannerButton: { borderRadius: 0, textTransform: "none" },
};
