person-subgraph:
  properties:
    workloadProfileName: Profile01
    configuration:
      registries:
        - server: racwa.azurecr.io
          username: ''
          passwordSecretRef: ''
          identity: /subscriptions/bc8c0622-7aa0-4a8b-8e07-9222ea6b0f02/resourceGroups/rg-next-rac-com-au-prd/providers/Microsoft.ManagedIdentity/userAssignedIdentities/next-rac-identity-prd
    template:
      containers:
        - image: racwa.azurecr.io/rac-digital/person-subgraph
          name: person-subgraph
          resources:
            cpu: 0.25
            memory: 0.5Gi
          securityContext:
            allowPrivilegeEscalation: false
          env:
            - name: APIM__ApiKey
              secretRef: digital-content-api-subscription-key
            - name: AzureMonitor__ConnectionString
              secretRef: app-insights-connection-string
            - name: ASPNETCORE_ENVIRONMENT
              value: prd
      scale:
        minReplicas: 2
        maxReplicas: 2

  identity:
    type: UserAssigned
    userAssignedIdentities:
      - /subscriptions/bc8c0622-7aa0-4a8b-8e07-9222ea6b0f02/resourceGroups/rg-next-rac-com-au-prd/providers/Microsoft.ManagedIdentity/userAssignedIdentities/next-rac-identity-prd
