import type { MenuItem } from "#types/horizons/menuItem";

import { colors, typography } from "@racwa/styles";

export const styles = {
  desktopMenu: {
    display: { xs: "none", md: "flex" },
  },
  desktopMenuAppBar: {
    backgroundColor: "#fff",
    boxShadow: "none",
  },
  desktopMenuUtilityToolbar: {
    display: "flex",
    justifyContent: "space-between",
    alignItems: "center",
    backgroundColor: colors.dieselDeepest,
  },
  desktopMenuPrimaryToolbar: {
    display: "flex",
    justifyContent: "space-between",
    alignItems: "center",
    height: "auto",
  },
  bar: (firstMenuItemOffsetLeft: number) => ({
    width: `${firstMenuItemOffsetLeft}px`,
    height: "20px",
    display: "flex",
    alignItems: "center",
    backgroundColor: "#FFFFFF",
    position: "relative",
    zIndex: 1,
    marginLeft: "-100%",
    top: "126px",
  }),
  triangle: {
    width: 0,
    height: 0,
    borderLeft: "10px solid transparent",
    borderRight: "10px solid transparent",
    borderTop: "20px solid white",
    position: "absolute",
    right: "-10px",
  },
  mobileMenu: {
    display: { xs: "flex", md: "none" },
  },
  topBarToolbar: {
    minHeight: "72px !important",
  },
  topBar: {
    display: "flex",
    justifyContent: "space-between",
    alignItems: "center",
  },
  topBarLogoWrapper: { display: "flex", alignItems: "center", gap: 1 },
  topBarLogoPrimary: { display: { sm: "flex", md: "none" } },
  topBarLogoSecondary: { display: { xs: "none", sm: "none", md: "flex" } },
  topBarMobileMenuIcon: { display: { sm: "flex", md: "none" } },
  navBarToolbar: {
    minHeight: "48px !important",
    display: { xs: "none", sm: "none", md: "flex" },
  },
  navBar: {
    justifyContent: "space-between",
    alignItems: "center",
  },
  navBarLogoAndMenuItemsWrapper: { display: "flex", alignItems: "center" },
  navBarMenuItemsWrapper: {
    display: "flex",
    height: "80px",
    m: 0,
    pl: 6,
    gap: 2,
  },
  menuItem: (item: MenuItem) => ({
    display: "flex",
    color: "#6F6F6F",
    borderRadius: 0,
    px: 0.5,
    pt: 3,
    "&::after": {
      content: '""',
      position: "absolute",
      left: 0,
      right: 0,
      bottom: 0,
      height: "5px",
      backgroundColor: item.contextualColour,
      transform: item.selected ? "scaleX(1)" : "scaleX(0)",
    },
    "&:hover::after": {
      transform: "scaleX(1)",
      height: "5px",
    },
  }),
  drawer: {
    width: 206,
    height: "100vh",
    backgroundColor: "#0C376B",
    fontFamily: typography.fontFamily,
    display: "flex",
    flexDirection: "column",
  },
  drawerMenuItem: {
    display: "flex",
    justifyContent: "flex-start",
    fontWeight: 400,
    textTransform: "none",
    color: "#FFFFFF",
    fontFamily: typography.fontFamily,
    fontSize: "15px",
    width: "100%",
    pl: 3,
  },
  drawerCloseButton: {
    position: "fixed",
    top: "10px",
    right: 212,
    backgroundColor: "#ffffff",
    borderRadius: "0px",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    width: "48px",
    height: "48px",
    zIndex: 9999,
  },
};
