import "@fortawesome/fontawesome-svg-core/styles.css";

import type { Metadata } from "next";
import { GoogleTagManager } from "@next/third-parties/google";
import Providers from "#components/Providers";
import { clientEnv } from "#env/client";
import { getServerSession } from "next-auth";

import { Qualtrics } from "@racwa/ui";

export const metadata: Metadata = {
  title: "Roadside Assistance - Change My Vehicle",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const session = await getServerSession();
  return (
    <html lang="en">
      <Providers sessionProps={{ session, basePath: clientEnv().NEXT_PUBLIC_AUTH_BASE_PATH }}>
        <body style={{ height: "100vh" }}>
          {children}
          <GoogleTagManager gtmId={clientEnv().NEXT_PUBLIC_GTM_ID} />
          <Qualtrics />
        </body>
      </Providers>
    </html>
  );
}
