name: Bump Version

outputs:
  semVer:
    description: "Semantic Version"
    value: ${{ steps.gitversion.outputs.semVer }}

runs:
  using: "composite"

  steps:
    - name: Install GitVersion
      uses: gittools/actions/gitversion/setup@v0
      with:
        versionSpec: "5.x"

    - name: Get Next Version
      id: gitversion
      uses: gittools/actions/gitversion/execute@v0
      with:
        useConfigFile: true

    - run: echo "Version number ${{ steps.gitversion.outputs.majorMinorPatch }}"
      shell: bash
      
