export type BackdropState = {
  open: boolean;
  message?: string;
};

/**
 * The type of MFA journey that the user is currently on.
 * This value will be used as the suffix when generating
 * the unique MFA session key that the RACI MFA OTP Service.
 * The session key generated by the backend will be used
 * as the suffix of the unique MFA session key.
 */
export const MfaJourneyType = {
  AccountRegistration: "my-rac-account-registration",
  ContactDetails: "my-rac-manage-contact-details",
} as const;
export type MfaJourneyTypeValue = (typeof MfaJourneyType)[keyof typeof MfaJourneyType];

export * from "./composites/OneTimePassword/types/index";
