export const styles = {
  instagramPostWrapper: {
    display: "flex",
    justifyContent: "center",
    width: "100%",
    margin: "auto",
    mb: 3,
    padding: "0 8px",
    "& blockquote": {
      margin: 0,
    },
  },
  instagramPost: {
    maxWidth: "540px",
    width: "100%",
    boxShadow: "none",
    borderRadius: "3px",
  },
  instagramPostLoader: { padding: "16px", border: "1px solid #DBDBDB" },
  instagramPostLoaderLinkWrapper: {
    background: "#FFFFFF",
    lineHeight: 0,
    textAlign: "center",
    width: "100%",
    display: "block",
  },
  instagramPostSkeletonWrapper1: { display: "flex", flexDirection: "row", alignItems: "center" },
  instagramPostSkeletonWrapper2: { display: "flex", flexDirection: "column", marginBottom: "24px" },
  instagramPostSkeletonAvatar: {
    backgroundColor: "#F4F4F4",
    borderRadius: "50%",
    flexGrow: 0,
    height: 40,
    width: 40,
    marginRight: "14px",
  },
  instagramPostSkeletonTextWrapper: { display: "flex", flexDirection: "column", flexGrow: 1, justifyContent: "center" },
  instagramPostSkeletonTextItem1: {
    backgroundColor: "#F4F4F4",
    borderRadius: "4px",
    height: "14px",
    marginBottom: "6px",
    width: "100px",
  },
  instagramPostSkeletonTextItem2: {
    backgroundColor: "#F4F4F4",
    borderRadius: "4px",
    height: "14px",
    width: "60px",
  },
  instagramPostSkeletonTextItem3: {
    backgroundColor: "#F4F4F4",
    borderRadius: "4px",
    height: "14px",
    marginBottom: "6px",
    width: "224px",
  },
  instagramPostSkeletonTextItem4: {
    backgroundColor: "#F4F4F4",
    borderRadius: "4px",
    height: "14px",
    width: "144px",
  },
  instagramPostViewPostText: {
    color: "#3897f0",
    fontSize: "14px",
    lineHeight: "18px",
  },
  instagramPostSkeletonMetadataWrapper: {
    display: "flex",
    flexDirection: "row",
    marginBottom: "14px",
    alignItems: "center",
  },
  instagramPostSkeletonLoveHeartLeft: {
    backgroundColor: "#F4F4F4",
    borderRadius: "50%",
    height: "12.5px",
    width: "12.5px",
    transform: "translateX(0px) translateY(7px)",
  },
  instagramPostSkeletonLoveHeartMiddle: {
    backgroundColor: "#F4F4F4",
    height: "12.5px",
    width: "12.5px",
    transform: "rotate(-45deg) translateX(3px) translateY(1px)",
    marginRight: "14px",
    marginLeft: "2px",
  },
  instagramPostSkeletonLoveHeartRight: {
    backgroundColor: "#F4F4F4",
    borderRadius: "50%",
    height: "12.5px",
    width: "12.5px",
    transform: "translateX(9px) translateY(-18px)",
  },
  instagramPostSkeletonCommentLeft: {
    backgroundColor: "#F4F4F4",
    borderRadius: "50%",
    height: "20px",
    width: "20px",
  },
  instagramPostSkeletonCommentRight: {
    width: 0,
    height: 0,
    borderTop: "2px solid transparent",
    borderLeft: "6px solid #f4f4f4",
    borderBottom: "2px solid transparent",
    transform: "translateX(16px) translateY(-4px) rotate(30deg)",
  },
  instagramPostSkeletonBookmarkLeft: {
    width: 0,
    borderTop: "8px solid #F4F4F4",
    borderRight: "8px solid transparent",
    transform: "translateY(16px)",
  },
  instagramPostSkeletonBookmarkMiddle: {
    backgroundColor: "#F4F4F4",
    height: "12px",
    width: "16px",
    transform: "translateY(-4px)",
  },
  instagramPostSkeletonBookmarkRight: {
    width: 0,
    height: 0,
    borderTop: "8px solid #F4F4F4",
    borderLeft: "8px solid transparent",
    transform: "translateY(-4px) translateX(8px)",
  },
};
