name: Get Keyvault Secret

# Would be good to get this to accept multiple secrets as input instead of 1 at a time

inputs:
  keyvault_name:
    required: true
    type: string
  secret_name:
    required: true
    type: string

outputs:
  secret:
    description: "Secret Value"
    value: ${{ steps.getSecret.outputs.secret }}

runs:
  using: "composite"

  steps:
    - name: Get Secret
      id: getSecret
      uses: azure/CLI@089eac9d8cc39f5d003e94f8b65efc51076c9cbd # v2
      with:
        inlineScript: |
          value=$(az keyvault secret show --name ${{ inputs.secret_name }} --vault-name ${{ inputs.keyvault_name }} --query value --output tsv)
          echo "::add-mask::$value"
          echo "secret=$value" >> "$GITHUB_OUTPUT"
