apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: appconfig
spec:
  type: configuration.azure.appconfig
  version: v1
  metadata:
  - name: host # Endpoint 
    value: https://next-rac-appconfig-sit.azconfig.io
  - name: subscribePollInterval
    value: 300s