apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: statestore
spec:
  type: state.in-memory
  version: v1
  metadata:
  - name: actorStateStore
    value: "true"

###uncomment below to use redis as state store

# apiVersion: dapr.io/v1alpha1
# kind: Component
# metadata:
#   name: statestore
# spec:
#   type: state.redis
#   version: v1
#   metadata:
#   - name: redisHost
#     value: localhost:6379
#   - name: redisPassword
#     value: ""
#   - name: actorStateStore
#     value: true
#   # - name: primaryEncryptionKey
#   #   secretKeyRef:
#   #     name: redis-primary-encryption-key
#   # - name: secondaryEncryptionKey
#   #   secretKeyRef:
#   #     name: redis-secondary-encryption-key
# auth:
#   secretStore: keyvault
