name: '🏗️ Infra: App Gateway (NPE)'

on:
  pull_request:
    paths:
      - .github/workflows/app_gateway_npe.yaml
      - infrastructure/application_gateway/npe/**
      - infrastructure/modules/terraform-azure-app-gateway/**
      - infrastructure/modules/web-application-firewallpolicy/**
    branches:
      - main

  push:
    paths:
      - .github/workflows/app_gateway_npe.yaml
      - infrastructure/application_gateway/npe/**
      - infrastructure/modules/terraform-azure-app-gateway/**
      - infrastructure/modules/web-application-firewallpolicy/**
    branches:
      - main

jobs:
  terraform:
    uses: ./.github/workflows/deploy_terraform_cloud_workflow.yaml
    permissions:
      id-token: write
      contents: read
      pull-requests: write
    with:
      arm_subscription_id: '4b737f05-03e2-4b5a-88a4-aa8264a39bed'
      blast_radius_calculation: true
      i_like_fun: true
      compare_plan: true
      use_saved_plan: true
      apply_empty_plan: false
      tf_dir: infrastructure/application_gateway/npe
      tf_apply_branch: main
      tf_skip_apply: ${{ github.event_name == 'pull_request' }}
      tf_apply_environment: npe
      tf_plan_environment: npe
      tf_backend_storage_account: 'racwaplatformtfstate'
      tf_backend_resource_group: 'platform-terraform-state'
      tf_backend_container: 'react-monorepo'
      tf_backend_key: 'application_gateway_npe.tfstate'
      tf_backend_subscription_id: '18ebc478-c4af-4365-a746-9026391a40da'
      tf_options_plan: -input=false
      tf_options_apply: -input=false -auto-approve
      use_federated_credentials: true
      tf_backend_use_azuread_auth: true
    secrets:
      PERSONAL_ACCESS_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
