name: Chromatic Visual UI Regression

on:
  pull_request:
    branches:
      - main
      - release/*
      - feature/*
    paths:
      - '**'
      # exclude static
      - '!.github/workflows/infrastructure_static_*.yaml'
      - '!infrastructure/static/**'
      - '!infrastructure/modules/container-app-environment/**'
      # exclude app gateway
      - '!.github/workflows/app_gateway_*.yaml'
      - '!infrastructure/application_gateway/**'
      - '!infrastructure/modules/terraform-azure-app-gateway/**'
env:
  keyvault_name: next-rac-vault-uat
  npm_token_secret_name: npm-token
  chromatic_secret_name: chromatic-token

jobs:
  chromatic-deployment:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Get NPM Token
        id: getNpmToken
        uses: ./.github/actions/get-keyvault-secret
        with:
          keyvault_name: ${{ env.keyvault_name }}
          secret_name: ${{ env.npm_token_secret_name }}
          perform_azure_login: true
        env:
          AZURE_CREDENTIALS: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Set up .npmrc file
        run: |
          echo "//racwa.pkgs.visualstudio.com/_packaging/racwa-design-feed/npm/registry/:username=racwa
          //racwa.pkgs.visualstudio.com/_packaging/racwa-design-feed/npm/registry/:_password=${{ steps.getNpmToken.outputs.secret }}
          //racwa.pkgs.visualstudio.com/_packaging/racwa-design-feed/npm/:username=racwa
          //racwa.pkgs.visualstudio.com/_packaging/racwa-design-feed/npm/:_password=${{ steps.getNpmToken.outputs.secret }}
          @racwa:registry=https://racwa.pkgs.visualstudio.com/_packaging/racwa-design-feed/npm/registry/
          always-auth=true" > ./frontend/.npmrc

      - name: Install pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 9

      - name: Install Chromatic via pnpm
        run: pnpm install
        working-directory: ./frontend

      - name: Get Chromatic Token
        id: getChromaticToken
        uses: ./.github/actions/get-keyvault-secret
        with:
          keyvault_name: ${{ env.keyvault_name }}
          secret_name: ${{ env.chromatic_secret_name }}

      - name: Publish to Chromatic
        uses: chromaui/action@v1
        with:
          projectToken: ${{ steps.getChromaticToken.outputs.secret }}
          workingDir: ./frontend
