name: '🎨 Frontend: Publish Chromatic'

on:
  workflow_dispatch:
  push:
    branches:
      - 'main'
    tags-ignore:
      - '*'
    paths:
      - 'frontend/apps/**'
      - 'frontend/packages/ui/**'
      - 'package.json'
      - 'pnpm-lock.yaml'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  publish_chromatic:
    name: Publish Chromatic
    runs-on: ubuntu-latest

    steps:
      - name: 👩‍💻 Checkout Repository
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4
        with:
          fetch-depth: 0

      - name: 🦺 Setup
        uses: ./.github/actions/setup
        with:
          npm-token: ${{ secrets.AZURE_NPM_TOKEN }}

      - name: 📢 Publish to Chromatic
        uses: chromaui/action@c93e0bc3a63aa176e14a75b61a31847cbfdd341c # v11.27.0
        with:
          projectToken: ${{ secrets.CHROMATIC_RAC_DIGITAL }}
          buildScriptName: build:storybook
          workingDir: ./frontend/apps/storybook
