name: '👈 Rollback Workflow'

on:
  workflow_dispatch:
    inputs:
      image_tag:
        description: 'Image tag to deploy'
        default: ''
        required: true
        type: string

jobs:
  check-image-version:
    runs-on: ubuntu-latest
    steps:
      - name: Azure Login
        uses: Azure/login@v1.1
        with:
          allow-no-subscriptions: true
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Verify Image tag
        shell: bash
        run: |
          az acr repository show -n racwa --image next-rac-com-au/next-rac-frontend:${{ inputs.image_tag }}
          az acr repository show -n racwa --image next-rac-com-au/next-rac-backend:${{ inputs.image_tag }}

  deploy_dev:
    name: Deploy Infrastructure DEV
    needs: [check-image-version]
    uses: ./.github/workflows/deploy_terraform_cloud_workflow.yaml
    with:
      arm_subscription_id: 4b737f05-03e2-4b5a-88a4-aa8264a39bed # digital-npe
      blast_radius_calculation: true
      i_like_fun: true
      use_saved_plan: true
      compare_plan: true
      apply_empty_plan: false
      tf_apply_environment: dev
      tf_dir: infrastructure/container-app/dev/
      tf_backend_key: "infrastructure_container_app_dev.tfstate"
      tf_options_plan: -input=false -var="image_version=${{ inputs.image_tag }}"
      tf_options_apply: -input=false -auto-approve
    secrets:
      AZURE_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
      AZURE_CLIENT_SECRET: ${{ secrets.AZURE_CLIENT_SECRET }}
      AZURE_CREDENTIALS: ${{ secrets.AZURE_CREDENTIALS }}
      AZURE_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}

  deploy_sit:
    name: Deploy Infrastructure (SIT)
    needs: [check-image-version]
    uses: ./.github/workflows/deploy_terraform_cloud_workflow.yaml
    with:
      arm_subscription_id: 4b737f05-03e2-4b5a-88a4-aa8264a39bed # digital-npe
      blast_radius_calculation: true
      i_like_fun: true
      use_saved_plan: true
      compare_plan: true
      apply_empty_plan: false
      tf_apply_environment: sit
      tf_dir: infrastructure/container-app/sit/
      tf_backend_key: "infrastructure_container_app_sit.tfstate"
      tf_options_plan: -input=false -var="image_version=${{ inputs.image_tag }}"
      tf_options_apply: -input=false -auto-approve
    secrets:
      AZURE_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
      AZURE_CLIENT_SECRET: ${{ secrets.AZURE_CLIENT_SECRET }}
      AZURE_CREDENTIALS: ${{ secrets.AZURE_CREDENTIALS }}
      AZURE_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}

  deploy_uat:
    name: Deploy Infrastructure (UAT)
    if: ${{ github.ref == 'refs/heads/main' || contains(github.ref, 'refs/heads/release/') || contains(github.ref, 'refs/heads/hotfix/') }}
    needs: [check-image-version]
    uses: ./.github/workflows/deploy_terraform_cloud_workflow.yaml
    with:
      arm_subscription_id: 4b737f05-03e2-4b5a-88a4-aa8264a39bed # digital-npe
      blast_radius_calculation: true
      i_like_fun: true
      use_saved_plan: true
      compare_plan: true
      apply_empty_plan: false
      tf_apply_environment: uat
      tf_dir: infrastructure/container-app/uat/
      tf_backend_key: "infrastructure_container_app_uat.tfstate"
      tf_options_plan: -input=false -var="image_version=${{ inputs.image_tag }}"
      tf_options_apply: -input=false -auto-approve
    secrets:
      AZURE_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
      AZURE_CLIENT_SECRET: ${{ secrets.AZURE_CLIENT_SECRET }}
      AZURE_CREDENTIALS: ${{ secrets.AZURE_CREDENTIALS }}
      AZURE_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}

  deploy_prd:
    name: Deploy Infrastructure (PRD)
    if: ${{ github.ref == 'refs/heads/main' }}
    needs: [check-image-version]
    uses: ./.github/workflows/deploy_terraform_cloud_workflow.yaml
    with:
      arm_subscription_id: bc8c0622-7aa0-4a8b-8e07-9222ea6b0f02 # digital-prd
      blast_radius_calculation: true
      i_like_fun: true
      use_saved_plan: true
      compare_plan: true
      apply_empty_plan: false
      tf_apply_environment: prd
      tf_dir: infrastructure/container-app/prd/
      tf_backend_key: "infrastructure_container_app_prd.tfstate"
      tf_options_plan: -input=false -var="image_version=${{ inputs.image_tag }}"
      tf_options_apply: -input=false -auto-approve
    secrets:
      AZURE_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
      AZURE_CLIENT_SECRET: ${{ secrets.AZURE_CLIENT_SECRET }}
      AZURE_CREDENTIALS: ${{ secrets.AZURE_CREDENTIALS }}
      AZURE_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}